### ISSUE TITLE
Support ALT attribute

### ISSUE THREAD

**Issue by ukmoose** [netsmarttech/node-red-contrib-ui-media#1]
Thanks for developing this, it would be great if it could also support the ALT attribute to define an alternative text description for images.

**Comment by glit0x63h** [comment]
Hi @ukmoose 
Thanks for your suggestion. Most of the image layouts set the image as div background. I'll look on alternatives to do the same for divs. Is `aria-label` equivalent to alt?

**Comment by tilleul** [comment]
``aria-label`` is for assistive technologies.
https://w3c.github.io/using-aria/#the-effect-of-accessible-name-on-background-images

Instead, if you don't use ``img`` tags why not provide a tooltip ?

**Comment by gfcittolin** [comment]
I'm closing this issue for now, as there's now support for configuring the "Tooltip" field, that sets the `title` attribute on the `div` that displays the image.
Please feel free to reopen the issue if the requirement is not fulfilled.
