### ISSUE TITLE
"Run on start" not working?

### ISSUE THREAD

**Issue by alastaira** [netsmarttech/node-red-contrib-ui-media#10]
Hi, thanks very much for this module!
I'm having problems getting the "Run on start" option to have any effect. Tested in both Firefox 69.0.3 (64-bit) or Edge 44.17763.771.0, but neither starts a video playing when the dahsboard is loaded - I have to enable "show controls" and manually click the play button. Wonder if this is a browser security feature?

Alternatively, is there a way to control video playback by passing in a payload value from the message flow? That would be a really useful feature. 

Thanks!

**Comment by alastaira** [comment]
Ha - why is it you always discover the answer to your own question moments after writing it!
I'd be trying to send msg.payload.play to the node, with no effect.
But msg.play works to start playback! So, I can trigger that from an inject node and it will work just fine, without needing the "Run on start" feature.

**Comment by steuck13** [comment]
Greetings
I'm glad you were able to figure it out. I'll take a look on the "Run on start" feature.
Ty for your report.
