### ISSUE TITLE
click on picture

### ISSUE THREAD

**Issue by debouttek** [netsmarttech/node-red-contrib-ui-media#15]
Hi, Thanks for making this media possible! Great job.

Is it possible to click on a picture and then go to a different page? Would we very nice to make new dashboards and make dashboards more responsive.

**Comment by gfcittolin** [comment]
This node has an output that, when an image is clicked, it emits a message with the mouse positions. So you could use a `change` node to set to the page you want, and then use the `ui_control` node to change to the desired page

**Comment by debouttek** [comment]
SUPER! Thanks.
