### ISSUE TITLE
Absolute path Error

### ISSUE THREAD

**Issue by Tolklein** [netsmarttech/node-red-contrib-ui-media#18]
I've installed the "node-red-contrib-ui-media" to display images within the dashboard, however as soon as I try add files via the "media" node I node-red crashes and I get the below error.
I've tried using the error catch node and debug node, but it still crashes, then I would need to delete the media node to get it to stop crashing.

I never had this issue running Rasbian or Ubuntu, and I am unsure how to resolve this under Windows 10.

I see the same error was reported and resolved in Version 1.1.3, (Issue #6) I'm running the version 1.2.0.
Any assistance would be greatly appreciated.

```
7 Jul 21:57:44 - [info] Starting flows
7 Jul 21:57:44 - [info] Started flows
8 Jul 09:58:43 - [red] Uncaught Exception:
8 Jul 09:58:43 - TypeError: path must be absolute or specify root to res.sendFile
at ServerResponse.sendFile (C:\Users\abcd\AppData\Roaming\npm\node_modules\node-red\node_modules\express\lib\response.js:425:11)
at C:\Users\abcd.node-red\node_modules\node-red-contrib-ui-media\ui_media.js:288:17
at FSReqCallback.oncomplete (fs.js:155:23)
PS C:\Windows\system32>
```

**Comment by sniicker** [comment]
Same Probleme !
I tried also to downgrade to Version 1.1.3, because it was the solution fo some others, but still does not work.

Pls help!

```
1 Sep 16:39:49 - [red] Uncaught Exception:
1 Sep 16:39:49 - TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (C:\Users\p.sojer\AppData\Roaming\npm\node_modules\node-red\node_modules\express\lib\response.js:425:11)
    at C:\Users\p.sojer\.node-red\node_modules\node-red-contrib-ui-media\ui_media.js:278:17
    at FSReqCallback.oncomplete (fs.js:156:23)
```

**Comment by gfcittolin** [comment]
I've just published version 2.0 with many improvements and (hopefully) a definitive fix for that. Could you please test it?

**Comment by sniicker** [comment]
Well Done 👍 
Works now

**Comment by adamelli** [comment]
It's crashing for me now. After I add a file with the "media" node, and deploy, node-red crashes and I get the error above. 

 Node-RED version: v1.2.6
 Node.js  version: v14.15.0
 Windows_NT 10.0.19041 x64 LE
Loading palette nodes
+-----------------------------------------------------
| uibuilder initialised:
|   root folder: C:\Users\auraynar\.node-red\uibuilder
|   version . .: 3.0.0
|   packages . : jquery,socket.io
+-----------------------------------------------------

**Comment by sniicker** [comment]
Check in the Palate Manager if you have the Version 2.0.0

**Comment by adamelli** [comment]
> Check in the Palate Manager if you have the Version 2.0.0

1.2.0

**Comment by sniicker** [comment]
1. deinstall the package with your palete manager
2. open your comand line tool and go to the home path (~.node-red)
3. run _npm install node-red-contrib-ui-media@2.0.0_
4. Restart NodeRed and Check Palete Manager for Version 2.0.0

**Comment by sniicker** [comment]
@gfcittolin please check why we cannot install the right version directly in node red 
Thx
