### ISSUE TITLE
Autoplay and stop the video by passing a payload

### ISSUE THREAD

**Issue by meakash** [netsmarttech/node-red-contrib-ui-media#19]
Hello all,
I am new to this Node red with no experience with HTML or CSS.

I am working with this node and i am able to add images and videos on the dashboard.

I want that an image should appear as the background, once a inject button is clicked the first video should be played and stopped after playing it once and then again the image to be shown. Is it possible with this node? 

If yes, then please guide me with this.

**Comment by gfcittolin** [comment]
Hi @meakash 
Unfortunately this is not possible with this node. For your goal, you'll probably want to use the `ui_template` node that comes with the dashboard, but you'll need to write some code there for it to work (possibly HTML, CSS and JS). I suggest you to take a look on the Node-RED forum (https://discourse.nodered.org/), there have been some discussions there already about applications similar to yours.
