### ISSUE TITLE
Not able to install the node

### ISSUE THREAD

**Issue by ArthurVnL** [netsmarttech/node-red-contrib-ui-media#2]
Hi this node look seriously awsome, but I am not able to install it in any way. For now I have tried to install it on my raspberry pi and on my android phone in termux, but eventually I will install it on an Iot2000. The problem is that I am not able to install the node, the node isn't in the palette list and I get errors when I install it thru the terminal. I am new in node red but require this node for a project, so can anybody help me because I tried everything I can, but maybe I just missed something. Thanks for the help!

**Comment by glit0x63h** [comment]
Running the command 
`npm install node-red-contrib-ui-media`
Seems to be working. Don't forget to restart node-red after installing new nodes. Can you post what error appear to you on install?

Also, I'll look what could be happening with install through Manage Palette. Thank you for pointing that out.

**Comment by glit0x63h** [comment]
Fixed with https://github.com/netsmarttech/node-red-contrib-ui-media/commit/8adefa5ef91631f0b6a521b9c52a58d2a066ca49

**Comment by ArthurVnL** [comment]
Thaaaanks aaa looot
