### ISSUE TITLE
msg.play does not start video until play controls clicked

### ISSUE THREAD

**Issue by arris138** [netsmarttech/node-red-contrib-ui-media#20]
Having an issue starting a video by injecting msg.play after restarting flow.  If I just inject that message, the video does not start.  If i enable controls, click play and then pause on screen, then msg.play and msg.pause injects work fine.  It's like the video has to be in focus or started before the injects work.  Am I setting up something wrong?

`[{"id":"c5331584.1e4af8","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"1228a925.ece137","type":"ui_media","z":"c5331584.1e4af8","group":"20ca1fa1.51ac4","name":"","width":"30","height":"18","order":1,"category":"Vid","file":"sample-mp4-file.mp4","layout":"center","showcontrols":false,"loop":false,"onstart":false,"scope":"local","tooltip":"","x":490,"y":180,"wires":[[]]},{"id":"d7ba9f9.3d47c6","type":"inject","z":"c5331584.1e4af8","name":"start","props":[{"p":"play","v":"1","vt":"str"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":100,"y":140,"wires":[["8f127de8.c01d7"]]},{"id":"98bb6e29.e0bf4","type":"inject","z":"c5331584.1e4af8","name":"pause","props":[{"p":"pause","v":"1","vt":"str"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":90,"y":240,"wires":[["659874fa.aa9d4c"]]},{"id":"659874fa.aa9d4c","type":"change","z":"c5331584.1e4af8","name":"","rules":[{"t":"set","p":"pause","pt":"msg","to":"1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":280,"y":244,"wires":[["1228a925.ece137"]]},{"id":"8f127de8.c01d7","type":"change","z":"c5331584.1e4af8","name":"","rules":[{"t":"set","p":"play","pt":"msg","to":"1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":290,"y":160,"wires":[["1228a925.ece137"]]},{"id":"20ca1fa1.51ac4","type":"ui_group","z":"","name":"Default","tab":"12299565.8dc37b","order":1,"disp":false,"width":30,"collapse":false},{"id":"12299565.8dc37b","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]`

**Comment by machadotiago** [comment]
Check if it is not related to this one:
https://github.com/netsmarttech/node-red-contrib-ui-media/issues/16
To test it just try the same setup with a video that is mute and has no sound (you can use a gif)

**Comment by arris138** [comment]
You're right - added muted and it seems to work fine. 

Using the following code seems to be a workaround by injecting msg.unmute a second later:
              if (msg.topic=="unmute") {
                var video = document.getElementById('video');
                video.muted = !video.muted;
            }

**Comment by machadotiago** [comment]
Depending on your application you can also set your chromium switches

**Comment by arris138** [comment]
Great, that's an even better solution.  Added the following to my chromium autostart and it works like a charm. 

--autoplay-policy=no-user-gesture-required

**Comment by machadotiago** [comment]
I’m closing this issue then.
