### ISSUE TITLE
Error when trying to use.

### ISSUE THREAD

**Issue by Just-another-pleb** [netsmarttech/node-red-contrib-ui-media#3]
I am running NR 0.20.3
Dashboard 12.14.0
Ubuntu 18.4.0 LTS

I get the node installed and I don't see any errors.   (Installed from Web page)
The node loads, but there seems to be a problem.

Pictures say 1,000 words.

Also, sorry, but your "walk through" on how to use it seems to be confusing.
From the page:
_To upload an image or a video you first must go to the File tab. Then you 'll click the icon to the right of the Category dropdown menu (left pic) and will give it a name like on the example (right pic)._
This is below two pictures which I can't equate to the sentence above.
Below is maybe the two pictures, but there is no "left/right" picture.   They are above one another.
For the sake of trying, I put something in the **category** field and get an error something about **API NOT FOUND.**

See pictures.
![Screenshot from 2019-04-06 21-39-51](https://user-images.githubusercontent.com/39888280/55668351-e6bcc800-58b4-11e9-9958-a827460aaa7b.png)
![Screenshot from 2019-04-06 21-39-53](https://user-images.githubusercontent.com/39888280/55668352-e6bcc800-58b4-11e9-804c-b739844290fa.png)
![Screenshot from 2019-04-06 21-40-02](https://user-images.githubusercontent.com/39888280/55668353-e7555e80-58b4-11e9-9989-9e589b436d91.png)

**Comment by steuck13** [comment]
Greetings
I'll try to reproduce your error.
Meanwhile, could post the node-red log?
Thank you

**Comment by Just-another-pleb** [comment]
Ok, shall post shortly.   But, as a pre-text:   Where is the node-red log?
I understand the "nodered log" is in /var/log/nodered-install.log
But that is the install log, rather than the error log.

**Comment by Just-another-pleb** [comment]
This is weird.

Went to the "node list" (left hand side of screen) and looked for `media`.  NOTHING FOUND!!!

Weird!  I didn't think I uninstalled it yesterday.

Went to "manage palette and searched "media" in installed nodes:

I don't know if this will be helping the situation


![Screenshot from 2019-04-07 07-22-45](https://user-images.githubusercontent.com/39888280/55675475-632bc700-5906-11e9-8447-2ea53e55f256.png)

**Comment by Just-another-pleb** [comment]
Uninstalled it and did it from the command line.

Got this:

npm install node-red-contrib-ui-media
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

+ node-red-contrib-ui-media@1.0.3
added 4 packages from 5 contributors and audited 1212 packages in 3.806s
found 4 vulnerabilities (2 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details


Force refreshed NR on the machine and looked at installed nodes (left side of screen).

Not there.

**Comment by Just-another-pleb** [comment]
I have it installed now and visible in the list.
I tried to put it in a flow and it errored. (spelling?)
I deleted it from the flow and DEPLOYED, all good.  No errors, but this is what I see in the palette manager now.

![Screenshot from 2019-04-07 08-03-47](https://user-images.githubusercontent.com/39888280/55675826-c835eb80-590b-11e9-8162-c686462191db.png)

**Comment by Just-another-pleb** [comment]
(Sorry....)
Going to the next step with debugging running I get this:
(not very helpful I believe)

.
.
.
7 Apr 08:09:05 - [info] [mqtt-broker:MQTT host] Connection failed to broker: mqtt://192.168.0.99:1883
7 Apr 08:09:05 - [info] [mqtt-broker:MQTT host] Connection failed to broker: mqtt://192.168.0.99:1883
7 Apr 08:09:22 - [info] [mqtt-broker:MQTT host] Connection failed to broker: mqtt://192.168.0.99:1883
7 Apr 08:09:22 - [info] [mqtt-broker:MQTT host] Connection failed to broker: mqtt://192.168.0.99:1883
7 Apr 08:09:29 - [info] Stopping modified nodes
7 Apr 08:09:29 - [info] Stopped modified nodes
7 Apr 08:09:29 - [info] Waiting for missing types to be registered:
7 Apr 08:09:29 - [info]  - ui_media

Helpful?

**Comment by steuck13** [comment]
Greetings,
Yes, very helpful. Thank you.
Aparently this is releated to a known issue with the projects directive on the settings.js file. We´ll be releasing a fix this week.

Thank your for reporting this to us.

**Comment by robingeek** [comment]
> Greetings,
> Yes, very helpful. Thank you.
> Aparently this is releated to a known issue with the projects directive on the settings.js file. We´ll be releasing a fix this week.
> 
> Thank your for reporting this to us.

I have seen the same bug on one of our instance but not on the other. Must be a difference in version or use of projects.

Looking forward to the fix.

Keep up the good work

Robin

**Comment by steuck13** [comment]
We released 1.0.5 with fixes for project related bugs.
