### ISSUE TITLE
Incorrect syntax in "info" for the node.

### ISSUE THREAD

**Issue by Just-another-pleb** [netsmarttech/node-red-contrib-ui-media#4]
I appreciate that the instruction are a **GUIDE** but:

>     Is possible to switch media by msg.src, using a link http.
    Example:
    msg.src: "https://http.cat/200.jpg" 

When it should be:

msg.src = "https://http.cat/200.jpg"

Wasted a lot of my time trying to work out why it wasn't working.

I still haven't got it working because - like so many other instructions - it is written for people who ALREADY know the answer and not to help people who don't, learn.

**Comment by gfcittolin** [comment]
Dear @Just-another-pleb,

The examples are not plain javascript code, just instructions to which property should be set to achieve the desired behavior. On Node-RED, we'd even discourage you to use javascript functions to set simple properties like this (as seems to be the case by your complain), and instead use change nodes for that.

Please also note that all the work you find in this repository (and many others here too) has been made by people trying to do their best and is made available on a free basis. Therefore, as an open community, we can discuss how would be the best way to represent it, in order not to cause such confusion in the future.
