### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by robingeek** [netsmarttech/node-red-contrib-ui-media#5]
Hi there,

I am trying to figure out an issue with broken images.
I am running NR 0.20.2
node-red-contrib-ui-media 1.0.5

The node configuration looks ok, creates a category, uploads images etc.
I can see the image files in 
~/.node-red/projects/MyProject/ui-media/lib/1st_run/
The image url in the dashboard is 
http://192.168.5.93:1880/uimedia/1st_run/serial_usb.jpg

Is there a problem with how it is linking/mapping files within a project?

Any help gratefully appreciated.

Cheers

Robin

**Comment by steuck13** [comment]
Greetings,

Currently I'm having some trouble reproducing your problem and seeing your screenshot. Could you upload it somewhere? 

Thank you for your report.

**Comment by robingeek** [comment]
Hi there, 
I may have found the issue.
We change some options in the settings.js file
httpAdminRoot: '/admin', 
ui: { path: "/" },

This makes the URL a bit cleaner but breaks the ui-media 
screenshot attached is with the above settings.

![media_broken](https://user-images.githubusercontent.com/5043219/56710112-a7c5b800-6778-11e9-9bca-3e7dc753ee5d.png)

If I comment those two options out then the ui-media works.
Any chance we could make ui-media work with the above options in settings.js?

Cheers

Robin

**Comment by robingeek** [comment]
Any chance we could make ui-media work with the these options in settings.js?
httpAdminRoot: '/admin',
ui: { path: "/" },

**Comment by steuck13** [comment]
We'll take a look into it.

Thank you for your suggestion.
