### ISSUE TITLE
Request example flow

### ISSUE THREAD

**Issue by Just-another-pleb** [netsmarttech/node-red-contrib-ui-media#8]
Could you please supply a sample flow where the message (any part) has the name of the picture to show.
Thanks in advance.

**Comment by gfcittolin** [comment]
Supposing that I have the following image uploaded...

![image](https://user-images.githubusercontent.com/2856088/64358907-b1401600-cfdd-11e9-9724-040018807bfc.png)

... you just need to send a message with the `payload` to the content of the "Link" field (that is, a string in the format `category/media`)

![image](https://user-images.githubusercontent.com/2856088/64359162-30cde500-cfde-11e9-88c9-1e7f76b4e218.png)

```json
{
  "payload": "logos/GitHub-Mark.png"
}
```

-----

You have also the possibility to send a custom url by setting the `src` property to the desired URL:

![image](https://user-images.githubusercontent.com/2856088/64360243-712e6280-cfe0-11e9-8fcd-d0e664a609cc.png)

```json
{
  "src":"https://github.githubassets.com/images/modules/logos_page/Octocat.png"
}
```

Here's the flow of the sceenshot above. Of course you'd need to reupload the image in your instance for it to work
```json
[{"id":"891baecd.e9f78","type":"inject","z":"c994dd82.874b5","name":"","topic":"","payload":"logos/GitHub-Mark.png","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":360,"y":240,"wires":[["f9e18d8e.d98e4","7d7de6eb.e337e8"]]},{"id":"f9e18d8e.d98e4","type":"ui_media","z":"c994dd82.874b5","group":"4071cd23.bc73a4","name":"","width":0,"height":0,"order":2,"category":"logos","file":"GitHub-Mark.png","layout":"adjust","showcontrols":true,"loop":true,"onstart":false,"scope":"local","tooltip":"","x":590,"y":300,"wires":[[]]},{"id":"7d7de6eb.e337e8","type":"debug","z":"c994dd82.874b5","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":590,"y":240,"wires":[]},{"id":"8199e8ba.1a10a8","type":"change","z":"c994dd82.874b5","name":"","rules":[{"t":"move","p":"payload","pt":"msg","to":"src","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":370,"y":360,"wires":[["f9e18d8e.d98e4","cb0a9c3d.05cd7"]]},{"id":"e4850fcf.a34bf","type":"inject","z":"c994dd82.874b5","name":"","topic":"","payload":"https://github.githubassets.com/images/modules/logos_page/Octocat.png","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":360,"wires":[["8199e8ba.1a10a8"]]},{"id":"cb0a9c3d.05cd7","type":"debug","z":"c994dd82.874b5","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":590,"y":360,"wires":[]},{"id":"4071cd23.bc73a4","type":"ui_group","z":"","name":"Test","tab":"63408704.e45268","disp":true,"width":"12","collapse":false},{"id":"63408704.e45268","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]
```

**Comment by Just-another-pleb** [comment]
I really appreciate the reply.

But I am still missing something.

The first example is what I thought/think it should be and how it should work.
But for me it doesn't.

Here is my flow:
```
[{"id":"98cf8386.ff45c8","type":"inject","z":"3dbe217c.10c666","name":"","topic":"","payload":"/home/me/Pictures/wood1.jpg","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":670,"wires":[["652e1b52.fa2744"]]},{"id":"652e1b52.fa2744","type":"ui_media","z":"3dbe217c.10c666","group":"46a62be5.f2b0ac","name":"","width":0,"height":0,"order":0,"category":"","file":"","layout":"adjust","showcontrols":true,"loop":true,"onstart":false,"scope":"local","tooltip":"","x":370,"y":670,"wires":[[]]},{"id":"46a62be5.f2b0ac","type":"ui_group","name":"Group 1","tab":"91f88c2e.8ab318","order":1,"disp":true,"width":6},{"id":"91f88c2e.8ab318","type":"ui_tab","name":"Tab 31","icon":"dashboard","order":31}]
```

This is what I see on the screen:
![Screenshot from 2019-09-06 06-57-43](https://user-images.githubusercontent.com/39888280/64380229-eb5bf700-d073-11e9-8d6e-934e5b4b9aee.png)

I seem to be missing something with the category/file/link bits.
The file names will be dynamic (not fixed) so I don't get how that all fits together.

Again, thanks for the help so far.

**Comment by Just-another-pleb** [comment]
Thanks  I think I suss'ed it out.

It didn't help I didn't have the `public` set in that machine's Node-Red.

**Comment by gfcittolin** [comment]
I see what to tried with your flow. The node doesn't expect a path to _any_ file in your machine, but a `<category>/<mediafile>`-formatted string that the node will resolve to files that have been uploaded to it, only.

What you can instead send a `msg.src` set to `file:///home/me/your-media-file`, but this will work only if the dashboard is being shown on the same machine where the files are hosted.

Another option would be to make Node-RED serve the images by using the `http in` and `http out` nodes, and then send the same `msg.src` but set to the path your `http in` node is listening to

**Comment by Just-another-pleb** [comment]
Again:  Thanks.

With NR set up with the public part it works.   As you explained - and I originally missed - I need it to be in msg.src not msg.payload.

It is also that one machine will have the pictures and another will access them.
But that was not working because I didn't have the public part in the settings.js configured correctly.

And, I was putting the entire remote path, rather than (eg)  192.168.0.91:/Pictures/(filename) rather than 192.168.0.91:/home/pi/.node-red/public/Pictures/(filename)   Doesn't work.

Sorry for bothering you.  I wasn't helping myself because of the settings not being set correctly in NR.   After a lot of "oops!' moments, I did get it working.

Though again:  Thanks.

**Comment by gfcittolin** [comment]
Great, never mind! Good luck there!
