### ISSUE TITLE
Dashboard Layout - Uncontrollable

### ISSUE THREAD

**Issue by beccsjb** [netsmarttech/node-red-contrib-ui-media#9]
Having issues with this media node; whenever i add it to a dashboard tab it completely messes up the dashboard layout. I've tried deleting all the spacers, then redoing the layout and deploying, doesnt resolve the issues. Remove the media node from an active tab and everything goes back to its right place.

Anyone else discovered this too?

**Comment by steuck13** [comment]
Greetings,
Would you mind sharing your flow so we could reproduce your problem?

Thank you

**Comment by beccsjb** [comment]
Howdy, the flow is rather simple, purely trying to get 2 different images to display depending on what payload the node receives.

[{"id":"96eee48d.97d058","type":"ui_media","z":"8fd95987.d99e18","group":"","name":"Hi-Low Indicator FAN","width":4,"height":3,"order":53,"category":"FAN","file":"FanON.gif","layout":"adjust","showcontrols":true,"loop":true,"onstart":false,"scope":"local","tooltip":"","x":1063,"y":3470,"wires":[[]]},{"id":"808bb9e8.25a368","type":"change","z":"8fd95987.d99e18","name":"","rules":[{"t":"change","p":"payload","pt":"msg","from":"ON","fromt":"str","to":"FAN/FanON.gif","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"OFF","fromt":"str","to":"FAN/FanOFF.png","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":702.9999999999999,"y":3483.999999999999,"wires":[["96eee48d.97d058"]]}].

**Comment by beccsjb** [comment]
The media node just seems to not be bound to the 'layout', despite being able to specifically locate it wherever you'd like, when you deploy it just seems to go wherever it wants and also messes up the layout of all the other dashboard nodes. Remove media node from that tab and everything goes back how it was again.

**Comment by beccsjb** [comment]
Has anyone else discovered the same or similar issue?

**Comment by steuck13** [comment]
Greetings
I'll take a look. 
Thank you for your report.

**Comment by beccsjb** [comment]
Any update on this @steuck13 ?

**Comment by steuck13** [comment]
Greetings,
Sorry, it's on my to-do list. I'll take a look at it when things calm down a bit.

**Comment by dceejay** [comment]
This is due to #12.
Somewhere around https://github.com/netsmarttech/node-red-contrib-ui-media/blob/master/ui_media.js#L640
just add
```
    order: config.order,
```

**Comment by gfcittolin** [comment]
Hi Dave, taking a look at it right now. 
I'm traveling right now, as soon as I have a stable connection I'll publish a new version with this and other fixes

**Comment by gfcittolin** [comment]
Hi,
Just published `1.2.0` that should solve this and the configuration panel issues as mentioned in #12. As a bonus, I've improved the help section, it should now reflect a bit better the accepted messages and their behavior.

Let me know if you have any other issue

(P.S.: I really hope that that warning about the order property not being set is not because solely of this node)

**Comment by dceejay** [comment]
no - we look for it on any node so that is easy to report to developers. (It wasn't just you.. :-)
